//! Proof Engine — Compliance Audit Binder.
//!
//! Generates the audit-ready evidence binder from DragonKeep's existing
//! framework mappings (MITRE ATT&CK, NIST SP 800-53, DISA STIG, CIS
//! Benchmarks). For each control referenced by a finding, Proof renders
//! a one-page evidence sheet: which control, how DragonKeep checked it,
//! whether the system passes or fails, and the remediation path.
//!
//! Output is Markdown by default; planned: PDF via Typst + LaTeX
//! fallback so the binder is a true deliverable.

use anyhow::Result;
use colored::Colorize;
use std::collections::BTreeMap;

use crate::config::Config;
use crate::engine::{Finding, Severity};

#[derive(Debug, Default, Clone)]
pub struct ProofSummary {
    pub controls_total: usize,
    pub controls_pass: usize,
    pub controls_fail: usize,
    pub frameworks_seen: BTreeMap<String, usize>,
}

impl ProofSummary {
    pub fn coverage_pct(&self) -> u32 {
        if self.controls_total == 0 {
            return 0;
        }
        ((self.controls_pass as f64 / self.controls_total as f64) * 100.0) as u32
    }
}

/// Run Proof against a set of findings (typically the output of a
/// scan). Returns findings summarizing the compliance posture.
pub async fn scan(_config: &Config, prior: &[Finding]) -> Result<Vec<Finding>> {
    let mut findings = Vec::new();
    eprintln!("    {} Building compliance summary...", "→".dimmed());

    let summary = summarize(prior);

    let pct = summary.coverage_pct();
    let title = format!(
        "Compliance coverage: {pct}% ({} of {} controls passing)",
        summary.controls_pass, summary.controls_total
    );
    let mut f = match pct {
        80..=100 => Finding::pass(title),
        60..79 => Finding::info(title),
        40..59 => Finding::warning(title),
        _ => Finding::high(title),
    };
    f = f.with_engine("Proof").with_rule("DK-PRF-001");
    findings.push(f);

    for (fw, n) in &summary.frameworks_seen {
        findings.push(
            Finding::info(format!("{fw}: {n} control reference(s)"))
                .with_engine("Proof")
                .with_rule("DK-PRF-002"),
        );
    }

    Ok(findings)
}

/// Aggregate framework references across findings.
pub fn summarize(findings: &[Finding]) -> ProofSummary {
    let mut sum = ProofSummary::default();
    for f in findings {
        let passes = matches!(f.severity, Severity::Pass);
        let mut counted_any = false;
        if let Some(mitre) = &f.mitre {
            for _ in mitre {
                sum.controls_total += 1;
                if passes {
                    sum.controls_pass += 1;
                } else {
                    sum.controls_fail += 1;
                }
                counted_any = true;
            }
            *sum.frameworks_seen.entry("MITRE ATT&CK".to_string()).or_insert(0) +=
                mitre.len();
        }
        if let Some(nist) = &f.nist {
            for _ in nist {
                sum.controls_total += 1;
                if passes {
                    sum.controls_pass += 1;
                } else {
                    sum.controls_fail += 1;
                }
                counted_any = true;
            }
            *sum.frameworks_seen.entry("NIST SP 800-53".to_string()).or_insert(0) +=
                nist.len();
        }
        if let Some(_) = &f.stig {
            sum.controls_total += 1;
            if passes {
                sum.controls_pass += 1;
            } else {
                sum.controls_fail += 1;
            }
            counted_any = true;
            *sum.frameworks_seen.entry("DISA STIG".to_string()).or_insert(0) += 1;
        }
        if let Some(_) = &f.cis_id {
            sum.controls_total += 1;
            if passes {
                sum.controls_pass += 1;
            } else {
                sum.controls_fail += 1;
            }
            counted_any = true;
            *sum.frameworks_seen.entry("CIS Benchmarks".to_string()).or_insert(0) += 1;
        }
        if !counted_any && !passes {
            // Unmapped finding — still counts against the binder
            sum.controls_total += 1;
            sum.controls_fail += 1;
        }
    }
    sum
}

/// Render the compliance binder as Markdown. Returns the full document.
pub fn render_markdown(findings: &[Finding]) -> String {
    let summary = summarize(findings);
    let mut out = String::new();
    out.push_str("# Compliance Audit Binder\n\n");
    out.push_str(&format!(
        "_Generated by DragonKeep Proof Engine · {}_\n\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));
    out.push_str("## Executive summary\n\n");
    out.push_str(&format!(
        "**Coverage:** {}% — {} of {} controls passing.\n\n",
        summary.coverage_pct(),
        summary.controls_pass,
        summary.controls_total
    ));
    if !summary.frameworks_seen.is_empty() {
        out.push_str("**Frameworks referenced:**\n\n");
        for (fw, n) in &summary.frameworks_seen {
            out.push_str(&format!("- {fw}: {n} control reference(s)\n"));
        }
        out.push('\n');
    }

    let failing: Vec<_> = findings
        .iter()
        .filter(|f| !matches!(f.severity, Severity::Pass | Severity::Info))
        .collect();
    if !failing.is_empty() {
        out.push_str("## Failing controls\n\n");
        for f in failing.iter().take(40) {
            out.push_str(&format!("### [{}] {}\n\n", f.severity.label(), f.title));
            if let Some(d) = &f.detail {
                out.push_str(d);
                out.push_str("\n\n");
            }
            if let Some(m) = &f.mitre {
                if !m.is_empty() {
                    out.push_str(&format!("- MITRE ATT&CK: `{}`\n", m.join(", ")));
                }
            }
            if let Some(n) = &f.nist {
                if !n.is_empty() {
                    out.push_str(&format!("- NIST SP 800-53: `{}`\n", n.join(", ")));
                }
            }
            if let Some(s) = &f.stig {
                out.push_str(&format!("- DISA STIG: `{s}`\n"));
            }
            if let Some(c) = &f.cis_id {
                out.push_str(&format!("- CIS Benchmark: `{c}`\n"));
            }
            if let Some(fix) = &f.fix {
                out.push_str(&format!("\n**Remediation:** {fix}\n"));
            }
            out.push('\n');
        }
    }
    out.push_str("\n---\n\nDragonKeep · Ghost Protocol (Pvt) Ltd · ghosts.lk\n");
    out
}
