//! Compliance templates and reporting for DragonKeep.
//!
//! Maps DragonKeep findings to industry compliance frameworks including
//! CIS Benchmarks, DISA STIGs, NIST SP 800-53, MITRE ATT&CK, PCI DSS,
//! HIPAA, and SOC 2.

use std::fmt;

use chrono::Utc;
use colored::Colorize;
use serde::{Deserialize, Serialize};
use tabled::{Table, Tabled, settings::{Style, Modify, object::Columns, Width}};

use crate::cli::OutputFormat;
use crate::engine::{Finding, Severity};

// ─── Enums ───────────────────────────────────────────────────────────────────

/// Supported compliance frameworks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ComplianceFramework {
    CIS,
    STIG,
    NIST80053,
    MITRE,
    #[serde(rename = "PCI_DSS")]
    PCI_DSS,
    HIPAA,
    SOC2,
}

impl fmt::Display for ComplianceFramework {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::CIS => write!(f, "CIS Benchmarks"),
            Self::STIG => write!(f, "DISA STIG"),
            Self::NIST80053 => write!(f, "NIST SP 800-53 Rev 5"),
            Self::MITRE => write!(f, "MITRE ATT&CK"),
            Self::PCI_DSS => write!(f, "PCI DSS v4.0"),
            Self::HIPAA => write!(f, "HIPAA Security Rule"),
            Self::SOC2 => write!(f, "SOC 2 Type II"),
        }
    }
}

/// Severity classification for a compliance control.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ControlSeverity {
    Required,
    Recommended,
    Optional,
}

impl fmt::Display for ControlSeverity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Required => write!(f, "Required"),
            Self::Recommended => write!(f, "Recommended"),
            Self::Optional => write!(f, "Optional"),
        }
    }
}

/// Evaluation status for a single control.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ControlStatus {
    Pass,
    Fail,
    NotApplicable,
    NotChecked,
}

impl fmt::Display for ControlStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Pass => write!(f, "PASS"),
            Self::Fail => write!(f, "FAIL"),
            Self::NotApplicable => write!(f, "N/A"),
            Self::NotChecked => write!(f, "NOT CHECKED"),
        }
    }
}

impl ControlStatus {
    pub fn colored_label(&self) -> String {
        match self {
            Self::Pass => "PASS".green().bold().to_string(),
            Self::Fail => "FAIL".red().bold().to_string(),
            Self::NotApplicable => "N/A".bright_black().to_string(),
            Self::NotChecked => "NOT CHECKED".yellow().to_string(),
        }
    }
}

// ─── Core structs ────────────────────────────────────────────────────────────

/// A single compliance control within a framework.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceControl {
    pub id: String,
    pub title: String,
    pub description: String,
    pub severity: ControlSeverity,
    pub finding_rules: Vec<String>,
    pub framework_ref: String,
}

/// A compliance template: a framework + its set of controls.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceTemplate {
    pub framework: ComplianceFramework,
    pub name: String,
    pub version: String,
    pub controls: Vec<ComplianceControl>,
}

/// The result of evaluating one control against scan findings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ControlResult {
    pub control: ComplianceControl,
    pub status: ControlStatus,
    pub findings: Vec<Finding>,
    pub evidence: Option<String>,
}

/// Full compliance report generated by [`check_compliance`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceReport {
    pub framework: ComplianceFramework,
    pub generated_at: String,
    pub hostname: String,
    pub total_controls: usize,
    pub passed: usize,
    pub failed: usize,
    pub not_applicable: usize,
    pub not_checked: usize,
    pub compliance_score: f32,
    pub results: Vec<ControlResult>,
}

// ─── Compliance checking engine ──────────────────────────────────────────────

/// Evaluate every control in `template` against the supplied `findings`.
///
/// Matching logic (checked in order):
/// 1. `Finding::rule_id` matches any entry in `ComplianceControl::finding_rules`
/// 2. `Finding::cis_id` matches the control id (for CIS controls)
/// 3. `Finding::stig` matches the control id (for STIG controls)
/// 4. `Finding::nist` contains the control id (for NIST controls)
///
/// Status derivation from matched findings:
/// - If any finding has `Severity::Pass` → `ControlStatus::Pass`
/// - If any finding has `Severity::Critical` or `Severity::High` → `ControlStatus::Fail`
/// - If any finding has `Severity::Warning` → `ControlStatus::Fail`
/// - If findings matched but all are `Severity::Info` → `ControlStatus::Pass`
/// - No findings matched → `ControlStatus::NotChecked`
pub fn check_compliance(template: &ComplianceTemplate, findings: &[Finding]) -> ComplianceReport {
    let hostname = hostname();

    let mut results = Vec::with_capacity(template.controls.len());
    let mut passed: usize = 0;
    let mut failed: usize = 0;
    let mut not_applicable: usize = 0;
    let mut not_checked: usize = 0;

    for control in &template.controls {
        let matched: Vec<Finding> = findings
            .iter()
            .filter(|f| finding_matches_control(f, control))
            .cloned()
            .collect();

        let (status, evidence) = if matched.is_empty() {
            (ControlStatus::NotChecked, None)
        } else {
            derive_status(&matched)
        };

        match status {
            ControlStatus::Pass => passed += 1,
            ControlStatus::Fail => failed += 1,
            ControlStatus::NotApplicable => not_applicable += 1,
            ControlStatus::NotChecked => not_checked += 1,
        }

        results.push(ControlResult {
            control: control.clone(),
            status,
            findings: matched,
            evidence,
        });
    }

    let total = template.controls.len();
    let evaluated = passed + failed;
    let score = if evaluated > 0 {
        (passed as f32 / evaluated as f32) * 100.0
    } else {
        0.0
    };

    ComplianceReport {
        framework: template.framework.clone(),
        generated_at: Utc::now().to_rfc3339(),
        hostname,
        total_controls: total,
        passed,
        failed,
        not_applicable,
        not_checked,
        compliance_score: (score * 10.0).round() / 10.0,
        results,
    }
}

fn finding_matches_control(finding: &Finding, control: &ComplianceControl) -> bool {
    // 1. rule_id match
    if let Some(ref rule_id) = finding.rule_id {
        if control.finding_rules.iter().any(|r| r == rule_id) {
            return true;
        }
    }

    // 2. CIS ID match
    if let Some(ref cis_id) = finding.cis_id {
        if control.id.ends_with(cis_id) || cis_id == &control.id {
            return true;
        }
    }

    // 3. STIG match
    if let Some(ref stig) = finding.stig {
        if stig == &control.id {
            return true;
        }
    }

    // 4. NIST match
    if let Some(ref nist_controls) = finding.nist {
        if nist_controls.iter().any(|n| n == &control.id) {
            return true;
        }
    }

    false
}

fn derive_status(matched: &[Finding]) -> (ControlStatus, Option<String>) {
    let has_pass = matched.iter().any(|f| f.severity == Severity::Pass);
    let has_critical = matched.iter().any(|f| f.severity == Severity::Critical);
    let has_high = matched.iter().any(|f| f.severity == Severity::High);
    let has_warning = matched.iter().any(|f| f.severity == Severity::Warning);

    if has_critical || has_high {
        let titles: Vec<&str> = matched
            .iter()
            .filter(|f| f.severity == Severity::Critical || f.severity == Severity::High)
            .map(|f| f.title.as_str())
            .collect();
        (
            ControlStatus::Fail,
            Some(format!("Failed: {}", titles.join("; "))),
        )
    } else if has_warning {
        let titles: Vec<&str> = matched
            .iter()
            .filter(|f| f.severity == Severity::Warning)
            .map(|f| f.title.as_str())
            .collect();
        (
            ControlStatus::Fail,
            Some(format!("Warnings: {}", titles.join("; "))),
        )
    } else if has_pass {
        (ControlStatus::Pass, Some("All checks passed".to_string()))
    } else {
        // Only Info-level findings → treat as pass
        (ControlStatus::Pass, Some("Informational only".to_string()))
    }
}

fn hostname() -> String {
    std::env::var("HOSTNAME")
        .or_else(|_| std::env::var("HOST"))
        .unwrap_or_else(|_| "unknown".to_string())
}

// ─── Pretty-print / render ───────────────────────────────────────────────────

/// Render a compliance report in the requested output format.
pub fn render_compliance_report(report: &ComplianceReport, format: &OutputFormat) -> String {
    match format {
        OutputFormat::Json => serde_json::to_string_pretty(report).unwrap_or_default(),
        OutputFormat::Minimal => render_minimal(report),
        _ => render_pretty(report),
    }
}

fn render_pretty(report: &ComplianceReport) -> String {
    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "\n{}\n",
        "╔══════════════════════════════════════════════════════════════╗"
            .bright_cyan()
    ));
    out.push_str(&format!(
        "{}  🏰 DragonKeep Compliance Report{}\n",
        "║".bright_cyan(),
        "                            ║".bright_cyan()
    ));
    out.push_str(&format!(
        "{}\n",
        "╚══════════════════════════════════════════════════════════════╝"
            .bright_cyan()
    ));

    // Summary
    out.push_str(&format!(
        "\n  {} {}\n",
        "Framework:".bold(),
        report.framework
    ));
    out.push_str(&format!("  {} {}\n", "Host:".bold(), report.hostname));
    out.push_str(&format!(
        "  {} {}\n",
        "Generated:".bold(),
        report.generated_at
    ));

    let score_colored = if report.compliance_score >= 80.0 {
        format!("{:.1}%", report.compliance_score).green().bold()
    } else if report.compliance_score >= 50.0 {
        format!("{:.1}%", report.compliance_score).yellow().bold()
    } else {
        format!("{:.1}%", report.compliance_score).red().bold()
    };
    out.push_str(&format!(
        "  {} {}\n\n",
        "Compliance Score:".bold(),
        score_colored
    ));

    out.push_str(&format!(
        "  {} {}  {} {}  {} {}  {} {}\n\n",
        "✓".green().bold(),
        format!("{} Passed", report.passed).green(),
        "✗".red().bold(),
        format!("{} Failed", report.failed).red(),
        "—".bright_black(),
        format!("{} N/A", report.not_applicable).bright_black(),
        "?".yellow(),
        format!("{} Not Checked", report.not_checked).yellow(),
    ));

    // Results table
    #[derive(Tabled)]
    struct Row {
        #[tabled(rename = "Status")]
        status: String,
        #[tabled(rename = "Control ID")]
        id: String,
        #[tabled(rename = "Title")]
        title: String,
        #[tabled(rename = "Severity")]
        severity: String,
        #[tabled(rename = "Evidence")]
        evidence: String,
    }

    let rows: Vec<Row> = report
        .results
        .iter()
        .map(|r| Row {
            status: r.status.colored_label(),
            id: r.control.id.clone(),
            title: truncate(&r.control.title, 40),
            severity: r.control.severity.to_string(),
            evidence: truncate(
                r.evidence.as_deref().unwrap_or("—"),
                50,
            ),
        })
        .collect();

    if !rows.is_empty() {
        let table = Table::new(&rows)
            .with(Style::rounded())
            .with(Modify::new(Columns::single(2)).with(Width::truncate(42).suffix("…")))
            .with(Modify::new(Columns::single(4)).with(Width::truncate(52).suffix("…")))
            .to_string();
        out.push_str(&table);
        out.push('\n');
    }

    out
}

fn render_minimal(report: &ComplianceReport) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "{} — {:.1}% ({}/{} passed)\n",
        report.framework,
        report.compliance_score,
        report.passed,
        report.passed + report.failed,
    ));
    for r in &report.results {
        if r.status == ControlStatus::Fail {
            out.push_str(&format!("  FAIL  {} — {}\n", r.control.id, r.control.title));
        }
    }
    out
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        format!("{}…", &s[..max - 1])
    }
}

// ─── Helper for building controls ───────────────────────────────────────────

fn ctrl(
    id: &str,
    title: &str,
    description: &str,
    severity: ControlSeverity,
    rules: &[&str],
    framework_ref: &str,
) -> ComplianceControl {
    ComplianceControl {
        id: id.to_string(),
        title: title.to_string(),
        description: description.to_string(),
        severity,
        finding_rules: rules.iter().map(|s| s.to_string()).collect(),
        framework_ref: framework_ref.to_string(),
    }
}

// ─── Built-in compliance templates ──────────────────────────────────────────

/// CIS Benchmarks — Level 1 (Server) for Linux.
///
/// Based on CIS Distribution Independent Linux Benchmark v2.0.0.
/// Covers filesystem, services, network, logging, access/auth, and file perms.
pub fn cis_linux_l1() -> ComplianceTemplate {
    use ControlSeverity::*;

    ComplianceTemplate {
        framework: ComplianceFramework::CIS,
        name: "CIS Distribution Independent Linux Benchmark — Level 1".to_string(),
        version: "2.0.0".to_string(),
        controls: vec![
            // ── 1. Filesystem Configuration ──
            ctrl(
                "CIS 1.1.1.1",
                "Ensure mounting of cramfs is disabled",
                "The cramfs filesystem type is a compressed read-only Linux filesystem. Disabling removes the ability to load the cramfs kernel module.",
                Required,
                &["DK-CIT-001"],
                "Section 1.1.1.1",
            ),
            ctrl(
                "CIS 1.1.1.2",
                "Ensure mounting of squashfs is disabled",
                "Squashfs is a compressed read-only filesystem. If not needed, disable it.",
                Required,
                &["DK-CIT-002"],
                "Section 1.1.1.2",
            ),
            ctrl(
                "CIS 1.1.1.3",
                "Ensure mounting of udf is disabled",
                "The udf filesystem type is the universal disk format used for DVDs/CDs.",
                Required,
                &["DK-CIT-003"],
                "Section 1.1.1.3",
            ),
            ctrl(
                "CIS 1.1.2",
                "Ensure /tmp is a separate partition",
                "The /tmp directory should be on a separate partition to prevent resource exhaustion.",
                Required,
                &["DK-CIT-010"],
                "Section 1.1.2",
            ),
            ctrl(
                "CIS 1.1.3",
                "Ensure noexec option set on /tmp",
                "Set noexec on /tmp to prevent execution of binaries from temporary storage.",
                Required,
                &["DK-CIT-011"],
                "Section 1.1.3",
            ),
            ctrl(
                "CIS 1.1.4",
                "Ensure nodev option set on /tmp",
                "Set nodev on /tmp to prevent creation of block/character special devices.",
                Required,
                &["DK-CIT-012"],
                "Section 1.1.4",
            ),
            ctrl(
                "CIS 1.1.5",
                "Ensure nosuid option set on /tmp",
                "Set nosuid on /tmp to prevent setuid programs from /tmp.",
                Required,
                &["DK-CIT-013"],
                "Section 1.1.5",
            ),

            // ── 2. Services ──
            ctrl(
                "CIS 2.1.1",
                "Ensure xinetd is not installed",
                "The extended Internet daemon (xinetd) is an open source super daemon. It should not be installed unless required.",
                Required,
                &["DK-CIT-020"],
                "Section 2.1.1",
            ),
            ctrl(
                "CIS 2.1.2",
                "Ensure telnet server is not installed",
                "The telnet-server package contains the telnet daemon, which accepts unencrypted connections.",
                Required,
                &["DK-SEN-010"],
                "Section 2.1.2",
            ),
            ctrl(
                "CIS 2.1.3",
                "Ensure rsh server is not installed",
                "The rsh-server service provides unencrypted remote access and should not be installed.",
                Required,
                &["DK-SEN-011"],
                "Section 2.1.3",
            ),
            ctrl(
                "CIS 2.1.4",
                "Ensure FTP server is not installed",
                "FTP transmits credentials in cleartext and should not be used.",
                Required,
                &["DK-SEN-012"],
                "Section 2.1.4",
            ),

            // ── 3. Network Configuration ──
            ctrl(
                "CIS 3.1.1",
                "Ensure IP forwarding is disabled",
                "IP forwarding allows the system to act as a router. Unless needed, disable it.",
                Required,
                &["DK-BAS-001"],
                "Section 3.1.1",
            ),
            ctrl(
                "CIS 3.1.2",
                "Ensure packet redirect sending is disabled",
                "ICMP redirect messages should not be sent to avoid MITM attacks.",
                Required,
                &["DK-BAS-002"],
                "Section 3.1.2",
            ),
            ctrl(
                "CIS 3.2.1",
                "Ensure source routed packets are not accepted",
                "Source-routed packets allow the sender to specify the route; this should be disabled.",
                Required,
                &["DK-BAS-003"],
                "Section 3.2.1",
            ),
            ctrl(
                "CIS 3.2.2",
                "Ensure ICMP redirects are not accepted",
                "ICMP redirect messages can be used to alter routing tables maliciously.",
                Required,
                &["DK-BAS-004"],
                "Section 3.2.2",
            ),
            ctrl(
                "CIS 3.4.1",
                "Ensure firewall package is installed",
                "A firewall utility is required to configure the Linux kernel's netfilter framework.",
                Required,
                &["DK-BAS-010"],
                "Section 3.4.1",
            ),
            ctrl(
                "CIS 3.4.2",
                "Ensure default deny firewall policy",
                "With a default deny policy, all inbound/outbound/forwarded traffic is denied by default.",
                Required,
                &["DK-BAS-011"],
                "Section 3.4.2",
            ),

            // ── 4. Logging and Auditing ──
            ctrl(
                "CIS 4.1.1",
                "Ensure auditd is installed",
                "auditd is the user-space component of the Linux Auditing System.",
                Required,
                &["DK-SEN-020"],
                "Section 4.1.1",
            ),
            ctrl(
                "CIS 4.1.2",
                "Ensure auditd service is enabled",
                "Enable the audit daemon to capture security-relevant events.",
                Required,
                &["DK-SEN-021"],
                "Section 4.1.2",
            ),
            ctrl(
                "CIS 4.2.1",
                "Ensure rsyslog is installed",
                "rsyslog provides reliable syslog message handling.",
                Required,
                &["DK-SEN-022"],
                "Section 4.2.1",
            ),
            ctrl(
                "CIS 4.2.2",
                "Ensure rsyslog service is enabled",
                "The rsyslog service must be running to capture system log messages.",
                Required,
                &["DK-SEN-023"],
                "Section 4.2.2",
            ),
            ctrl(
                "CIS 4.2.3",
                "Ensure log file permissions are configured",
                "Log files should have appropriate permissions to prevent unauthorized access.",
                Recommended,
                &["DK-SEN-024"],
                "Section 4.2.3",
            ),

            // ── 5. Access, Authentication and Authorization ──
            ctrl(
                "CIS 5.2.1",
                "Ensure permissions on /etc/ssh/sshd_config are configured",
                "The SSH daemon configuration file must be owned by root and not world-readable.",
                Required,
                &["DK-SEN-001"],
                "Section 5.2.1",
            ),
            ctrl(
                "CIS 5.2.4",
                "Ensure SSH access is limited",
                "Restrict which users and groups can access the system via SSH.",
                Required,
                &["DK-SEN-005"],
                "Section 5.2.4",
            ),
            ctrl(
                "CIS 5.2.5",
                "Ensure SSH root login is disabled",
                "Disallow direct root login over SSH to enforce accountability.",
                Required,
                &["DK-SEN-002"],
                "Section 5.2.5",
            ),
            ctrl(
                "CIS 5.2.6",
                "Ensure SSH PermitEmptyPasswords is disabled",
                "Prevent login to accounts with empty passwords over SSH.",
                Required,
                &["DK-SEN-003"],
                "Section 5.2.6",
            ),
            ctrl(
                "CIS 5.3.1",
                "Ensure password creation requirements are configured",
                "Strong password policies using pam_pwquality or equivalent.",
                Required,
                &["DK-CIT-030"],
                "Section 5.3.1",
            ),
            ctrl(
                "CIS 5.4.1",
                "Ensure password expiration is configured",
                "Set PASS_MAX_DAYS to ensure passwords are changed regularly.",
                Recommended,
                &["DK-CIT-031"],
                "Section 5.4.1",
            ),
            ctrl(
                "CIS 5.4.2",
                "Ensure sudo is installed and configured",
                "sudo allows granular privilege escalation instead of using root directly.",
                Required,
                &["DK-CIT-032"],
                "Section 5.4.2",
            ),

            // ── 6. File Permissions ──
            ctrl(
                "CIS 6.1.1",
                "Ensure permissions on /etc/passwd are configured",
                "/etc/passwd should be owned by root:root with permissions 644.",
                Required,
                &["DK-SEN-030"],
                "Section 6.1.1",
            ),
            ctrl(
                "CIS 6.1.2",
                "Ensure permissions on /etc/shadow are configured",
                "/etc/shadow should be owned by root:shadow with permissions 640 or more restrictive.",
                Required,
                &["DK-SEN-031"],
                "Section 6.1.2",
            ),
            ctrl(
                "CIS 6.1.3",
                "Ensure permissions on /etc/group are configured",
                "/etc/group should be owned by root:root with permissions 644.",
                Required,
                &["DK-SEN-032"],
                "Section 6.1.3",
            ),
            ctrl(
                "CIS 6.1.4",
                "Ensure permissions on crontab files are configured",
                "Crontab files should have restrictive permissions to prevent unauthorized job scheduling.",
                Required,
                &["DK-SEN-033"],
                "Section 6.1.4",
            ),
        ],
    }
}

/// CIS Benchmarks — Level 2 (Server) for Linux.
///
/// Extends Level 1 with stricter controls for higher-security environments.
pub fn cis_linux_l2() -> ComplianceTemplate {
    use ControlSeverity::*;

    let mut l1 = cis_linux_l1();
    l1.name = "CIS Distribution Independent Linux Benchmark — Level 2".to_string();

    let l2_controls = vec![
        ctrl(
            "CIS 1.1.6",
            "Ensure separate partition exists for /var",
            "Placing /var on a separate partition limits the impact of log or spool exhaustion.",
            Required,
            &["DK-CIT-014"],
            "Section 1.1.6",
        ),
        ctrl(
            "CIS 1.1.7",
            "Ensure separate partition exists for /var/tmp",
            "Isolating /var/tmp prevents temporary file attacks from filling /var.",
            Required,
            &["DK-CIT-015"],
            "Section 1.1.7",
        ),
        ctrl(
            "CIS 1.1.8",
            "Ensure separate partition exists for /var/log",
            "Protect log data by isolating /var/log on its own partition.",
            Required,
            &["DK-CIT-016"],
            "Section 1.1.8",
        ),
        ctrl(
            "CIS 1.1.9",
            "Ensure separate partition exists for /var/log/audit",
            "Audit logs must not be lost due to disk pressure from other data.",
            Required,
            &["DK-CIT-017"],
            "Section 1.1.9",
        ),
        ctrl(
            "CIS 1.1.10",
            "Ensure separate partition exists for /home",
            "Isolating user home directories prevents user data from filling the root partition.",
            Required,
            &["DK-CIT-018"],
            "Section 1.1.10",
        ),
        ctrl(
            "CIS 3.3.1",
            "Ensure TCP SYN cookies are enabled",
            "SYN cookies protect against SYN flood attacks by avoiding allocation until the handshake completes.",
            Required,
            &["DK-BAS-020"],
            "Section 3.3.1",
        ),
        ctrl(
            "CIS 3.3.2",
            "Ensure IPv6 router advertisements are not accepted",
            "Disable IPv6 router advertisements to prevent rogue RA attacks.",
            Required,
            &["DK-BAS-021"],
            "Section 3.3.2",
        ),
        ctrl(
            "CIS 4.1.3",
            "Ensure audit log storage size is configured",
            "Configure max_log_file in auditd.conf to prevent audit log loss.",
            Required,
            &["DK-SEN-025"],
            "Section 4.1.3",
        ),
        ctrl(
            "CIS 4.1.4",
            "Ensure audit logs are not automatically deleted",
            "Set max_log_file_action to keep_logs so audit data is preserved for review.",
            Required,
            &["DK-SEN-026"],
            "Section 4.1.4",
        ),
        ctrl(
            "CIS 5.2.7",
            "Ensure SSH MaxAuthTries is set to 4 or less",
            "Limiting authentication attempts reduces brute-force risk.",
            Required,
            &["DK-SEN-006"],
            "Section 5.2.7",
        ),
        ctrl(
            "CIS 5.2.8",
            "Ensure SSH Idle Timeout Interval is configured",
            "Configure ClientAliveInterval and ClientAliveCountMax to disconnect idle sessions.",
            Required,
            &["DK-SEN-007"],
            "Section 5.2.8",
        ),
        ctrl(
            "CIS 5.2.9",
            "Ensure SSH HostbasedAuthentication is disabled",
            "Disable host-based authentication which trusts remote host identity.",
            Required,
            &["DK-SEN-008"],
            "Section 5.2.9",
        ),
        ctrl(
            "CIS 5.2.10",
            "Ensure only strong ciphers are used for SSH",
            "Weak ciphers (3DES, RC4, etc.) must not be allowed.",
            Required,
            &["DK-SEN-009"],
            "Section 5.2.10",
        ),
        ctrl(
            "CIS 5.5.1",
            "Ensure account lockout policy is configured",
            "Lock accounts after repeated failed login attempts to mitigate brute-force.",
            Required,
            &["DK-CIT-033"],
            "Section 5.5.1",
        ),
        ctrl(
            "CIS 6.2.1",
            "Ensure no world-writable files exist",
            "World-writable files can be modified by any user and pose a security risk.",
            Required,
            &["DK-SEN-034"],
            "Section 6.2.1",
        ),
    ];

    l1.controls.extend(l2_controls);
    l1
}

/// DISA STIG for Red Hat Enterprise Linux 8.
pub fn stig_rhel8() -> ComplianceTemplate {
    use ControlSeverity::*;

    ComplianceTemplate {
        framework: ComplianceFramework::STIG,
        name: "DISA STIG Red Hat Enterprise Linux 8".to_string(),
        version: "V1R13".to_string(),
        controls: vec![
            ctrl(
                "RHEL-08-010010",
                "RHEL 8 must implement NIST FIPS-validated cryptography",
                "The system must use FIPS 140-2/3 validated cryptographic modules for all cryptographic operations.",
                Required,
                &["DK-CIT-040"],
                "SRG-OS-000033-GPOS-00014",
            ),
            ctrl(
                "RHEL-08-010020",
                "RHEL 8 must use a separate file system for /var",
                "Having a separate /var partition prevents log/spool data from filling the root filesystem.",
                Required,
                &["DK-CIT-014"],
                "SRG-OS-000480-GPOS-00227",
            ),
            ctrl(
                "RHEL-08-010030",
                "RHEL 8 must encrypt all stored passwords with SHA-512",
                "Passwords must be stored using SHA-512 hashing to prevent offline cracking.",
                Required,
                &["DK-CIT-041"],
                "SRG-OS-000073-GPOS-00041",
            ),
            ctrl(
                "RHEL-08-010040",
                "RHEL 8 must enforce password complexity by requiring at least one uppercase character",
                "The pam_pwquality module must require at least one uppercase letter (ucredit=-1).",
                Required,
                &["DK-CIT-030"],
                "SRG-OS-000069-GPOS-00037",
            ),
            ctrl(
                "RHEL-08-010050",
                "RHEL 8 must enforce password complexity by requiring at least one special character",
                "The pam_pwquality module must require at least one special character (ocredit=-1).",
                Required,
                &["DK-CIT-030"],
                "SRG-OS-000266-GPOS-00101",
            ),
            ctrl(
                "RHEL-08-010060",
                "RHEL 8 must enforce minimum password length of 15 characters",
                "Minimum password length must be set to 15 or more in /etc/security/pwquality.conf.",
                Required,
                &["DK-CIT-042"],
                "SRG-OS-000078-GPOS-00046",
            ),
            ctrl(
                "RHEL-08-010070",
                "RHEL 8 must prevent the use of dictionary words for passwords",
                "pam_pwquality dictcheck must be enabled to reject dictionary-based passwords.",
                Required,
                &["DK-CIT-043"],
                "SRG-OS-000480-GPOS-00225",
            ),
            ctrl(
                "RHEL-08-010110",
                "RHEL 8 must display a banner before granting access",
                "Display a DoD-approved login banner to warn unauthorized users.",
                Required,
                &["DK-CIT-044"],
                "SRG-OS-000023-GPOS-00006",
            ),
            ctrl(
                "RHEL-08-010150",
                "RHEL 8 must not allow accounts configured with blank or null passwords",
                "Ensure nullok is not present in PAM configuration files.",
                Required,
                &["DK-SEN-003"],
                "SRG-OS-000480-GPOS-00227",
            ),
            ctrl(
                "RHEL-08-010200",
                "RHEL 8 must disable the rsh-server package",
                "The rsh-server package transmits data unencrypted and must be removed.",
                Required,
                &["DK-SEN-011"],
                "SRG-OS-000095-GPOS-00049",
            ),
            ctrl(
                "RHEL-08-010300",
                "RHEL 8 must set SSH PermitRootLogin to no",
                "Direct root login over SSH must be disabled.",
                Required,
                &["DK-SEN-002"],
                "SRG-OS-000109-GPOS-00056",
            ),
            ctrl(
                "RHEL-08-010400",
                "RHEL 8 must enable audit logging",
                "The auditd service must be enabled and running.",
                Required,
                &["DK-SEN-021"],
                "SRG-OS-000037-GPOS-00015",
            ),
            ctrl(
                "RHEL-08-010500",
                "RHEL 8 must enable SELinux in enforcing mode",
                "SELinux must be configured in enforcing mode to enforce mandatory access controls.",
                Required,
                &["DK-CIT-045"],
                "SRG-OS-000445-GPOS-00199",
            ),
            ctrl(
                "RHEL-08-010600",
                "RHEL 8 must configure firewalld to rate-limit connections",
                "Use firewalld rich rules to limit connection rates and prevent DoS.",
                Recommended,
                &["DK-BAS-012"],
                "SRG-OS-000420-GPOS-00186",
            ),
            ctrl(
                "RHEL-08-010700",
                "RHEL 8 must not have unnecessary accounts",
                "System accounts for removed software or unused services must be deleted.",
                Required,
                &["DK-CIT-046"],
                "SRG-OS-000480-GPOS-00227",
            ),
            ctrl(
                "RHEL-08-010800",
                "RHEL 8 SSH daemon must not allow GSSAPI authentication",
                "GSSAPIAuthentication must be set to no unless Kerberos is in use.",
                Recommended,
                &["DK-SEN-040"],
                "SRG-OS-000364-GPOS-00151",
            ),
            ctrl(
                "RHEL-08-010900",
                "RHEL 8 SSH daemon must use strong MACs",
                "Only FIPS-validated MACs must be used for SSH connections.",
                Required,
                &["DK-SEN-041"],
                "SRG-OS-000250-GPOS-00093",
            ),
            ctrl(
                "RHEL-08-020000",
                "RHEL 8 must lock accounts after 3 consecutive failed logon attempts",
                "pam_faillock must lock accounts after 3 consecutive failures.",
                Required,
                &["DK-CIT-033"],
                "SRG-OS-000021-GPOS-00005",
            ),
            ctrl(
                "RHEL-08-020010",
                "RHEL 8 must enforce 24-hour minimum password lifetime",
                "PASS_MIN_DAYS must be set to 1 or more to prevent rapid password cycling.",
                Required,
                &["DK-CIT-047"],
                "SRG-OS-000075-GPOS-00043",
            ),
            ctrl(
                "RHEL-08-020020",
                "RHEL 8 must enforce 60-day maximum password lifetime",
                "PASS_MAX_DAYS must be set to 60 or less.",
                Required,
                &["DK-CIT-031"],
                "SRG-OS-000076-GPOS-00044",
            ),
        ],
    }
}

/// NIST SP 800-53 Rev 5 — Moderate baseline.
///
/// Covers control families: AC, AU, CM, IA, SC, SI.
pub fn nist_800_53_moderate() -> ComplianceTemplate {
    use ControlSeverity::*;

    ComplianceTemplate {
        framework: ComplianceFramework::NIST80053,
        name: "NIST SP 800-53 Rev 5 — Moderate Baseline".to_string(),
        version: "Rev 5".to_string(),
        controls: vec![
            // ── AC: Access Control ──
            ctrl(
                "AC-2",
                "Account Management",
                "Manage system accounts including establishing, activating, modifying, reviewing, disabling, and removing accounts.",
                Required,
                &["DK-CIT-046", "DK-CIT-033"],
                "AC Family",
            ),
            ctrl(
                "AC-3",
                "Access Enforcement",
                "Enforce approved authorizations for logical access to information and system resources.",
                Required,
                &["DK-CIT-045", "DK-SEN-005"],
                "AC Family",
            ),
            ctrl(
                "AC-6",
                "Least Privilege",
                "Employ the principle of least privilege, allowing only authorized accesses for users and processes.",
                Required,
                &["DK-CIT-032", "DK-SEN-002"],
                "AC Family",
            ),
            ctrl(
                "AC-7",
                "Unsuccessful Logon Attempts",
                "Enforce a limit of consecutive invalid logon attempts and automatically lock the account.",
                Required,
                &["DK-CIT-033"],
                "AC Family",
            ),
            ctrl(
                "AC-8",
                "System Use Notification",
                "Display an approved system use notification message before granting access.",
                Required,
                &["DK-CIT-044"],
                "AC Family",
            ),
            ctrl(
                "AC-17",
                "Remote Access",
                "Establish usage restrictions, configuration requirements, and implementation guidance for remote access.",
                Required,
                &["DK-SEN-001", "DK-SEN-005", "DK-SEN-002"],
                "AC Family",
            ),

            // ── AU: Audit and Accountability ──
            ctrl(
                "AU-2",
                "Event Logging",
                "Identify the types of events that the system is capable of logging in support of the audit function.",
                Required,
                &["DK-SEN-020", "DK-SEN-021"],
                "AU Family",
            ),
            ctrl(
                "AU-3",
                "Content of Audit Records",
                "Ensure audit records contain sufficient information to establish what occurred, when, where, source, and outcome.",
                Required,
                &["DK-SEN-025"],
                "AU Family",
            ),
            ctrl(
                "AU-6",
                "Audit Record Review, Analysis, and Reporting",
                "Review and analyze audit records for indications of inappropriate or unusual activity.",
                Recommended,
                &["DK-SEN-026"],
                "AU Family",
            ),
            ctrl(
                "AU-8",
                "Time Stamps",
                "Use internal system clocks to generate time stamps for audit records.",
                Required,
                &["DK-CIT-050"],
                "AU Family",
            ),
            ctrl(
                "AU-12",
                "Audit Record Generation",
                "Provide audit record generation capability and allow authorized personnel to select which events to audit.",
                Required,
                &["DK-SEN-020", "DK-SEN-021", "DK-SEN-022"],
                "AU Family",
            ),

            // ── CM: Configuration Management ──
            ctrl(
                "CM-2",
                "Baseline Configuration",
                "Develop, document, and maintain a current baseline configuration of the system.",
                Required,
                &["DK-CIT-001", "DK-CIT-002", "DK-CIT-003"],
                "CM Family",
            ),
            ctrl(
                "CM-6",
                "Configuration Settings",
                "Establish and document configuration settings for IT products using security configuration checklists.",
                Required,
                &["DK-CIT-010", "DK-CIT-011", "DK-CIT-012", "DK-CIT-013"],
                "CM Family",
            ),
            ctrl(
                "CM-7",
                "Least Functionality",
                "Configure the system to provide only mission-essential capabilities and prohibit or restrict use of unnecessary functions/ports/protocols/services.",
                Required,
                &["DK-CIT-020", "DK-SEN-010", "DK-SEN-011", "DK-SEN-012"],
                "CM Family",
            ),
            ctrl(
                "CM-8",
                "System Component Inventory",
                "Develop and document an inventory of system components that accurately reflects the system.",
                Recommended,
                &["DK-AGS-001"],
                "CM Family",
            ),

            // ── IA: Identification and Authentication ──
            ctrl(
                "IA-2",
                "Identification and Authentication (Organizational Users)",
                "Uniquely identify and authenticate organizational users.",
                Required,
                &["DK-CIT-030", "DK-CIT-041"],
                "IA Family",
            ),
            ctrl(
                "IA-5",
                "Authenticator Management",
                "Manage system authenticators by verifying identity, establishing initial content, and ensuring adequate strength.",
                Required,
                &["DK-CIT-030", "DK-CIT-031", "DK-CIT-042"],
                "IA Family",
            ),
            ctrl(
                "IA-6",
                "Authentication Feedback",
                "Obscure feedback of authentication information during the authentication process.",
                Recommended,
                &["DK-SEN-003"],
                "IA Family",
            ),
            ctrl(
                "IA-8",
                "Identification and Authentication (Non-Organizational Users)",
                "Uniquely identify and authenticate non-organizational users.",
                Recommended,
                &["DK-SEN-005"],
                "IA Family",
            ),

            // ── SC: System and Communications Protection ──
            ctrl(
                "SC-7",
                "Boundary Protection",
                "Monitor and control communications at the external managed interfaces and at key internal boundaries.",
                Required,
                &["DK-BAS-010", "DK-BAS-011"],
                "SC Family",
            ),
            ctrl(
                "SC-8",
                "Transmission Confidentiality and Integrity",
                "Protect the confidentiality and integrity of transmitted information.",
                Required,
                &["DK-SEN-009", "DK-CIT-040"],
                "SC Family",
            ),
            ctrl(
                "SC-12",
                "Cryptographic Key Establishment and Management",
                "Establish and manage cryptographic keys using approved mechanisms.",
                Required,
                &["DK-CIT-040"],
                "SC Family",
            ),
            ctrl(
                "SC-13",
                "Cryptographic Protection",
                "Implement FIPS-validated cryptography in accordance with applicable laws and policies.",
                Required,
                &["DK-CIT-040", "DK-CIT-041"],
                "SC Family",
            ),

            // ── SI: System and Information Integrity ──
            ctrl(
                "SI-2",
                "Flaw Remediation",
                "Identify, report, and correct system flaws in a timely manner and test the resulting updates.",
                Required,
                &["DK-AGS-002"],
                "SI Family",
            ),
            ctrl(
                "SI-3",
                "Malicious Code Protection",
                "Implement malicious code protection mechanisms at system entry and exit points.",
                Required,
                &["DK-HYD-001", "DK-DRK-001"],
                "SI Family",
            ),
            ctrl(
                "SI-4",
                "System Monitoring",
                "Monitor the system to detect attacks and indicators of potential attacks, unauthorized connections, and anomalous behavior.",
                Required,
                &["DK-PHN-001", "DK-TAL-001"],
                "SI Family",
            ),
        ],
    }
}

/// PCI DSS v4.0 — Requirements 1–6 (network, data protection, vulnerability management, access control).
pub fn pci_dss_v4() -> ComplianceTemplate {
    use ControlSeverity::*;

    ComplianceTemplate {
        framework: ComplianceFramework::PCI_DSS,
        name: "PCI DSS v4.0".to_string(),
        version: "4.0".to_string(),
        controls: vec![
            // ── Requirement 1: Install and Maintain Network Security Controls ──
            ctrl(
                "PCI 1.2.1",
                "Restrict inbound and outbound traffic to that which is necessary",
                "Network security controls must restrict all other traffic and deny by default.",
                Required,
                &["DK-BAS-010", "DK-BAS-011"],
                "Requirement 1.2.1",
            ),
            ctrl(
                "PCI 1.2.5",
                "All services, protocols, and ports allowed are identified and approved",
                "All allowed services/ports must be documented and authorized.",
                Required,
                &["DK-BAS-001", "DK-BAS-002"],
                "Requirement 1.2.5",
            ),
            ctrl(
                "PCI 1.3.1",
                "Inbound traffic to the CDE is restricted to only necessary traffic",
                "Inbound traffic to the cardholder data environment must be minimized.",
                Required,
                &["DK-BAS-003", "DK-BAS-004"],
                "Requirement 1.3.1",
            ),

            // ── Requirement 2: Apply Secure Configurations ──
            ctrl(
                "PCI 2.2.1",
                "Configuration standards are developed and applied",
                "Develop configuration standards for all system components consistent with industry-accepted hardening standards.",
                Required,
                &["DK-CIT-001", "DK-CIT-002", "DK-CIT-003"],
                "Requirement 2.2.1",
            ),
            ctrl(
                "PCI 2.2.2",
                "Vendor default accounts are managed",
                "Default accounts, passwords, and unnecessary services are removed or disabled.",
                Required,
                &["DK-SEN-003", "DK-CIT-020"],
                "Requirement 2.2.2",
            ),
            ctrl(
                "PCI 2.2.4",
                "Only necessary services and protocols are enabled",
                "All unnecessary functionality is removed and only documented services are enabled.",
                Required,
                &["DK-SEN-010", "DK-SEN-011", "DK-SEN-012"],
                "Requirement 2.2.4",
            ),

            // ── Requirement 3: Protect Stored Account Data ──
            ctrl(
                "PCI 3.5.1",
                "Strong cryptography is used to render stored PAN unreadable",
                "Primary account numbers (PAN) must be rendered unreadable using strong cryptography.",
                Required,
                &["DK-CIT-040"],
                "Requirement 3.5.1",
            ),

            // ── Requirement 4: Protect Cardholder Data with Strong Cryptography During Transmission ──
            ctrl(
                "PCI 4.2.1",
                "Strong cryptography is used during transmission of PAN",
                "Strong cryptographic protocols must be used when PAN is transmitted over open public networks.",
                Required,
                &["DK-SEN-009", "DK-CIT-040"],
                "Requirement 4.2.1",
            ),

            // ── Requirement 5: Protect All Systems Against Malware ──
            ctrl(
                "PCI 5.2.1",
                "Anti-malware solution is deployed on all applicable systems",
                "An anti-malware solution must be deployed on all systems commonly affected by malicious software.",
                Required,
                &["DK-HYD-001", "DK-DRK-001"],
                "Requirement 5.2.1",
            ),
            ctrl(
                "PCI 5.3.1",
                "Anti-malware mechanisms are kept current",
                "Anti-malware mechanisms and definitions must be kept current via automatic updates.",
                Required,
                &["DK-HYD-001"],
                "Requirement 5.3.1",
            ),

            // ── Requirement 6: Develop and Maintain Secure Systems and Software ──
            ctrl(
                "PCI 6.2.1",
                "Custom software is developed securely",
                "Software development must follow secure coding guidelines (e.g., OWASP).",
                Required,
                &["DK-AGS-001", "DK-AGS-002"],
                "Requirement 6.2.1",
            ),
            ctrl(
                "PCI 6.3.1",
                "Security vulnerabilities are identified and addressed",
                "A process is defined to identify security vulnerabilities using reputable outside sources and assign risk rankings.",
                Required,
                &["DK-AGS-002"],
                "Requirement 6.3.1",
            ),
            ctrl(
                "PCI 6.3.3",
                "Security patches are applied within defined timeframes",
                "Critical patches must be installed within one month of release.",
                Required,
                &["DK-AGS-002"],
                "Requirement 6.3.3",
            ),
            ctrl(
                "PCI 6.4.1",
                "Public-facing web applications are protected against attacks",
                "Use WAFs or automated vulnerability tools to protect public-facing web applications.",
                Recommended,
                &["DK-BAS-012"],
                "Requirement 6.4.1",
            ),
            ctrl(
                "PCI 6.5.1",
                "Changes to system components are managed securely",
                "Change control procedures must be followed for all changes to system components.",
                Required,
                &["DK-SEN-020", "DK-SEN-021"],
                "Requirement 6.5.1",
            ),
        ],
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::{Finding, Severity};

    #[test]
    fn cis_l1_has_at_least_30_controls() {
        let t = cis_linux_l1();
        assert!(
            t.controls.len() >= 30,
            "CIS L1 should have ≥30 controls, got {}",
            t.controls.len()
        );
    }

    #[test]
    fn cis_l2_extends_l1() {
        let l1 = cis_linux_l1();
        let l2 = cis_linux_l2();
        assert!(l2.controls.len() > l1.controls.len());
    }

    #[test]
    fn stig_has_at_least_20_controls() {
        let t = stig_rhel8();
        assert!(
            t.controls.len() >= 20,
            "STIG RHEL8 should have ≥20 controls, got {}",
            t.controls.len()
        );
    }

    #[test]
    fn nist_has_at_least_25_controls() {
        let t = nist_800_53_moderate();
        assert!(
            t.controls.len() >= 25,
            "NIST 800-53 should have ≥25 controls, got {}",
            t.controls.len()
        );
    }

    #[test]
    fn pci_has_at_least_15_controls() {
        let t = pci_dss_v4();
        assert!(
            t.controls.len() >= 15,
            "PCI DSS should have ≥15 controls, got {}",
            t.controls.len()
        );
    }

    #[test]
    fn check_compliance_all_pass() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::CIS,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![ctrl(
                "CIS 5.2.5",
                "SSH root login disabled",
                "desc",
                ControlSeverity::Required,
                &["DK-SEN-002"],
                "5.2.5",
            )],
        };

        let findings = vec![Finding::pass("SSH root login is disabled").with_rule("DK-SEN-002")];
        let report = check_compliance(&template, &findings);

        assert_eq!(report.passed, 1);
        assert_eq!(report.failed, 0);
        assert!((report.compliance_score - 100.0).abs() < f32::EPSILON);
    }

    #[test]
    fn check_compliance_fail_on_high() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::STIG,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![ctrl(
                "RHEL-08-010300",
                "SSH PermitRootLogin",
                "desc",
                ControlSeverity::Required,
                &["DK-SEN-002"],
                "SRG",
            )],
        };

        let findings = vec![Finding::high("SSH root login enabled").with_rule("DK-SEN-002")];
        let report = check_compliance(&template, &findings);

        assert_eq!(report.failed, 1);
        assert_eq!(report.passed, 0);
        assert!((report.compliance_score - 0.0).abs() < f32::EPSILON);
    }

    #[test]
    fn check_compliance_not_checked() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::NIST80053,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![ctrl(
                "AC-2",
                "Account Management",
                "desc",
                ControlSeverity::Required,
                &["DK-CIT-099"],
                "AC",
            )],
        };

        let findings = vec![Finding::pass("Unrelated finding").with_rule("DK-SEN-002")];
        let report = check_compliance(&template, &findings);

        assert_eq!(report.not_checked, 1);
        assert_eq!(report.passed, 0);
        assert_eq!(report.failed, 0);
    }

    #[test]
    fn check_compliance_matches_by_cis_id() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::CIS,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![ctrl(
                "CIS 5.2.4",
                "SSH access limited",
                "desc",
                ControlSeverity::Required,
                &[],
                "5.2.4",
            )],
        };

        let findings = vec![Finding::pass("SSH access is limited").with_cis("5.2.4")];
        let report = check_compliance(&template, &findings);
        assert_eq!(report.passed, 1);
    }

    #[test]
    fn check_compliance_matches_by_nist() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::NIST80053,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![ctrl(
                "AC-6",
                "Least Privilege",
                "desc",
                ControlSeverity::Required,
                &[],
                "AC",
            )],
        };

        let findings = vec![Finding::pass("Sudo configured").with_nist(vec!["AC-6", "CM-6"])];
        let report = check_compliance(&template, &findings);
        assert_eq!(report.passed, 1);
    }

    #[test]
    fn render_json_round_trips() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::PCI_DSS,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![ctrl(
                "PCI 1.2.1",
                "Restrict traffic",
                "desc",
                ControlSeverity::Required,
                &["DK-BAS-010"],
                "1.2.1",
            )],
        };

        let findings = vec![Finding::pass("Firewall OK").with_rule("DK-BAS-010")];
        let report = check_compliance(&template, &findings);
        let json = render_compliance_report(&report, &OutputFormat::Json);

        let parsed: ComplianceReport = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.framework, ComplianceFramework::PCI_DSS);
        assert_eq!(parsed.passed, 1);
    }

    #[test]
    fn render_pretty_contains_summary() {
        let template = cis_linux_l1();
        let report = check_compliance(&template, &[]);
        let pretty = render_compliance_report(&report, &OutputFormat::Pretty);

        assert!(pretty.contains("Compliance Report"));
        assert!(pretty.contains("CIS Benchmarks"));
    }

    #[test]
    fn framework_display() {
        assert_eq!(format!("{}", ComplianceFramework::CIS), "CIS Benchmarks");
        assert_eq!(format!("{}", ComplianceFramework::STIG), "DISA STIG");
        assert_eq!(
            format!("{}", ComplianceFramework::NIST80053),
            "NIST SP 800-53 Rev 5"
        );
        assert_eq!(format!("{}", ComplianceFramework::PCI_DSS), "PCI DSS v4.0");
        assert_eq!(
            format!("{}", ComplianceFramework::HIPAA),
            "HIPAA Security Rule"
        );
        assert_eq!(format!("{}", ComplianceFramework::SOC2), "SOC 2 Type II");
    }

    #[test]
    fn control_severity_display() {
        assert_eq!(format!("{}", ControlSeverity::Required), "Required");
        assert_eq!(format!("{}", ControlSeverity::Recommended), "Recommended");
        assert_eq!(format!("{}", ControlSeverity::Optional), "Optional");
    }

    #[test]
    fn compliance_score_percentage() {
        let template = ComplianceTemplate {
            framework: ComplianceFramework::CIS,
            name: "Test".to_string(),
            version: "1.0".to_string(),
            controls: vec![
                ctrl("C1", "Pass control", "d", ControlSeverity::Required, &["DK-SEN-001"], "r"),
                ctrl("C2", "Fail control", "d", ControlSeverity::Required, &["DK-SEN-002"], "r"),
                ctrl("C3", "Unchecked", "d", ControlSeverity::Required, &["DK-SEN-099"], "r"),
            ],
        };

        let findings = vec![
            Finding::pass("OK").with_rule("DK-SEN-001"),
            Finding::critical("BAD").with_rule("DK-SEN-002"),
        ];

        let report = check_compliance(&template, &findings);
        assert_eq!(report.passed, 1);
        assert_eq!(report.failed, 1);
        assert_eq!(report.not_checked, 1);
        assert!((report.compliance_score - 50.0).abs() < f32::EPSILON);
    }
}
